config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    post 'users/sign_up' => 'users/registrations#create'
    get 'users/edit/update_password' => 'users/registrations#update_password'
    get 'users/edit/close_account' => 'users/registrations#close_account'
    post 'users/edit/close_account' => 'users/registrations#close_account_action'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'not_implemented', to: 'application#not_implemented'
  post 'not_implemented', to: 'application#not_implemented'

  resources :users, only: :show
  resources :events
  resources :user_event_permissions, only: :create
  delete 'user_event_permissions', to: 'user_event_permissions#destroy'

  root 'events#index'
end

app/views/navbar/_chevron_svg.html.erb
<div class="relative text-current w-4 h-4 text-[#6f7287]">
  <%= inline_svg_tag 'svg/chevron.svg'%>
</div>

app/views/navbar/_drop_down_dots.html.erb
<% set_content_for :label do %>
  <%= inline_svg_tag 'svg/dots.svg', class: 'h-6 w-6' %>
  <span class="sr-only">Menu</span>
<% end %>
<% set_content_for :list do %>
  <li><%= link_to 'Organize', not_implemented_path %></li>
  <li><%= link_to 'Help', not_implemented_path %></li>
  <li> <%= link_to 'Create an event', new_event_path, class: 'text-blue-600 hover:text-blue-600'  %></li>
<% end %>
<% set_content_for :chevron do %>
<% end %>

app/views/navbar/_drop_down_event.html.erb
<% set_content_for :label do %>
  <div class="hover:bg-gray-100 h-full w-full flex justify-center items-center">
    <%= inline_svg_tag 'svg/dots.svg', class:'h-6 w-6' %>
  </div>
  <span class="pl-2 text-[13px] font-normal">Menu</span>
<% end %>
<% set_content_for :list do %>
  <li><%= link_to 'Organize', not_implemented_path %></li>
  <li class="border-b-[1px] border-b-gray-100"><%= link_to 'Help', not_implemented_path %></li>
  <li class=" "> <%= link_to 'Create an event', new_event_path, class: 'text-blue-600 hover:text-blue-600'  %>
  </li>
  <%= render 'navbar/log_in_items' %>
<% end %>
<% set_content_for :chevron do %>
  <%= inline_svg_tag 'svg/chevron.svg', class: 'h-5 w-4 mt-1 hidden lg:block' %>
<% end %>

app/views/navbar/_drop_down_event_user.html.erb
<div class="group flex-col h-full justify-center items-center relative" x-data="{dropdown: false}">
  <div class="h-full flex flex-row justify-center items-center  text-[#6f7287] hover:text-[#39364f]" @click="dropdown = ! dropdown">
    <span class="pl-2 font-semibold text-xs text-[#1e0a3c] hidden lg:block"><%= current_user.name %></span>
    <div :class="dropdown && 'rotate-180'">
      <div class="flex items-center justify-center ml-2 mr-1">
        <%= inline_svg_tag 'svg/chevron.svg', class: 'h-4 w-4 text-[#39364f]' %>
      </div>
    </div>
  </div>
  <ul class="absolute min-w-[250px] right-0 self-end bg-white text-sm font-normal shadow-lg rounded text-[#39364f]
   [&>*]:pr-5 [&>*]:pl-6 [&>*]:py-4 [&>*:hover]:cursor-pointer  [&>*:hover]:text-gray-800 [&>*:hover]:bg-gray-100
    top-[49px]" x-show="dropdown" x-cloak @click.outside="dropdown=false">
    <li><%= link_to not_implemented_path do %>
        <div class="flex">
          <div class="flex flex-col mr-4">
            <%= inline_svg_tag 'svg/arrow_right.svg', class: 'h-3 w-7' %>
            <%= inline_svg_tag 'svg/arrow_right.svg', class: 'h-3 w-7 rotate-180' %>
          </div>
          <span class="">Switch to attending</span>
        </div>
      <% end %>
    </li>
    <li class='border-b border-b-[#eeedf2]'><%= link_to edit_user_registration_path do %>
        <div class="flex">
          <span class="mr-4"><%= inline_svg_tag 'svg/user_placeholder.svg', class: 'h-6 w-6'  %></span>
          <span class="">Account Settings</span>
        </div>
      <% end %>
    </li>
    <li ><%= button_to destroy_user_session_path, method: :delete do %>
        <div class="flex">
          <span class="mr-4"><%= inline_svg_tag 'svg/log_out.svg', class: 'h-6 w-6'  %></span>
          <span class="text-ellipsis clamp-one text-left">Log out <%= current_user.email %></span>
        </div>
      <% end %>
    </li>
    <li class="cursor-not-allowed"><span ><%= current_user.name.titleize %></span></li>
  </ul>
</div>
<% set_content_for :label do %>
  <span class="pl-2 font-semibold text-xs text-[#1e0a3c] hidden lg:block"><%= current_user.name %></span>
<% end %>
<% set_content_for :chevron do %>
  <div class="flex items-center justify-center ml-2 mr-1">
    <%= inline_svg_tag 'svg/chevron.svg', class: 'h-4 w-4 text-[#39364f]' %>
  </div>
<% end %>
<% set_content_for :picture do %>
  <div class="flex bg-[#3659e3] rounded-full h-8 w-8 items-center justify-center">
    <span class="text-white text-[10px] leading-5 font-semibold"><%= current_user.name[0...2].upcase %></span>
  </div>
<% end %>
<% set_content_for :list do %>
  <li><%= link_to not_implemented_path do %>
      <div class="flex">
        <div class="flex flex-col mr-4">
          <%= inline_svg_tag 'svg/arrow_right.svg', class: 'h-3 w-7' %>
          <%= inline_svg_tag 'svg/arrow_right.svg', class: 'h-3 w-7 rotate-180' %>
        </div>
        <span class="">Switch to attending</span>
      </div>
    <% end %>
  </li>
  <li class='border-b border-b-[#eeedf2]'><%= link_to edit_user_registration_path do %>
      <div class="flex">
        <span class="mr-4"><%= inline_svg_tag 'svg/user_placeholder.svg', class: 'h-6 w-6'  %></span>
        <span class="">Account Settings</span>
      </div>
    <% end %>
  </li>
  <li ><%= button_to destroy_user_session_path, method: :delete do %>
      <div class="flex">
        <span class="mr-4"><%= inline_svg_tag 'svg/log_out.svg', class: 'h-6 w-6'  %></span>
        <span class="text-ellipsis clamp-one text-left">Log out <%= current_user.email %></span>
      </div>
    <% end %>
  </li>
  <li class="cursor-not-allowed"><span ><%= current_user.name.titleize %></span></li>
<% end %>

app/views/navbar/_drop_down_help.html.erb
<% set_content_for :label do %>
  Help
<% end %>
<% set_content_for :list do %>
  <li><%= link_to 'Find your tickets', not_implemented_path %></li>
  <li><%= link_to 'Contact an event organizer', not_implemented_path %></li>
  <li><%= link_to 'Visit the help center', not_implemented_path  %></li>
<% end %>
<% set_content_for :chevron do %>
  <%= inline_svg_tag 'svg/chevron.svg', class: 'h-5 w-4 mt-1' %>
<% end %>

app/views/navbar/_drop_down_organize.html.erb
<% set_content_for :label do %>
  <span class="hidden lg:block">Organize</span>
<% end %>
<% set_content_for :list do %>
  <li><%= link_to 'Why Eventbrite?', not_implemented_path %></li>
  <li><%= link_to 'Pricing', not_implemented_path %></li>
  <li><%= link_to 'Resources', not_implemented_path %></li>
<% end %>
<% set_content_for :chevron do %>
  <%= inline_svg_tag 'svg/chevron.svg', class: 'h-5 w-4 mt-1' %>
<% end %>

app/views/navbar/_drop_down_user.html.erb
<% set_content_for :picture do %>
  <div class="flex items-center justify-center lg:bg-gray-100 rounded-full lg:h-10 lg:w-10" aria-label="Site Menu" >
    <%= inline_svg_tag 'svg/user_placeholder.svg', class:'h-6 w-6' %>
  </div>
<% end %>
<% set_content_for :label do %>
  <span class="pl-2 hidden lg:block"><%= current_user.email %></span>
<% end %>
<% set_content_for :list do %>
  <li><%= link_to 'Create an event', new_event_path, class: 'text-blue-600 hover:text-blue-600' %></li>
  <li class="border-b-[1px] border-gray-100">
    <%= link_to 'Browse Events', events_path %>
  </li>
  <li><%= link_to 'Tickets (0)', not_implemented_path %></li>
  <li><%= link_to 'Credits', not_implemented_path %></li>
  <li><%= link_to 'Liked', not_implemented_path %></li>
  <li><%= link_to 'Following', not_implemented_path %></li>
  <li><%= link_to 'Interests', not_implemented_path %></li>
  <li class=" border-t-[1px] border-gray-100">
    <%= link_to 'Account Settings', edit_user_registration_path %>
  </li>
  <li>
    <div class="flex truncate text-[#a9a8b3] cursor-not-allowed clamp-one">
      <%= current_user.email %>
    </div>
  </li>
  <li><%= button_to 'Log Out', destroy_user_session_path, method: :delete %></li>
  <li class=" border-t-[1px] border-gray-100
    <%= local_assigns[:is_event_view] ? 'hidden' : 'lg:hidden'%>">
    <%= link_to 'Organize', not_implemented_path %>
  </li>
  <li class="<%= local_assigns[:is_event_view] ? 'hidden' : 'lg:hidden'%>">
    <%= link_to 'Help', not_implemented_path %>
  </li>
<% end %>
<% set_content_for :chevron do %>
  <%= inline_svg_tag 'svg/chevron.svg', class: 'h-5 w-4 mt-1 hidden lg:block' %>
<% end %>

app/views/navbar/_log_in_items.html.erb
<% unless user_signed_in? %>
  <%= link_to 'Log In', new_user_session_path, class: "flex h-full flex-col justify-center hover:text-[#39364f]" %>
  <%= link_to 'Sign Up', new_user_registration_path, class: "flex h-full flex-col justify-center hover:text-[#39364f]" %>
<% end %>

app/views/navbar/_navbar.html.erb
<nav id="header-nav" class="bg-white w-full min-h-[72px] flex flex-row justify-evenly z-20 border-b-[1px] border-b-[#eeedf2]">
  <ul class='flex flex-row font-semibold text-[13px] w-full items-center justify-center' style="color: #39364f">
    <%= link_to root_path, 'aria-label': 'Home' do %>
      <%= inline_svg_tag 'svg/eventbrite_logo.svg', class:'h-[20px] px-6 text-cur', style: 'fill: #f05537' %>
    <% end %>
    <%= render 'navbar/search' %>
    <% if user_signed_in? %>
      <%= render 'navbar/signed_in_items' %>
    <% else %>
      <%= render 'navbar/signed_out_items' %>
    <% end %>
  </ul>
</nav>

app/views/navbar/_navbar_event.html.erb
<nav id="header-nav" class="bg-white w-full min-h-[60px] flex flex-row z-20 border-b-[1px] border-[#eeedf2]">
  <ul class='w-full flex flex-row font-normal text-[13px] items-center justify-center text-[#6f7287]'>
    <%= link_to root_path, 'aria-label': 'Home' do %>
      <%= inline_svg_tag 'svg/eventbrite_logo.svg', class:'h-[20px] px-6 text-cur', style: 'fill: #f05537' %>
    <% end %>
    <%= render partial: 'navbar/search', locals: { is_event_view: true} %>
    <%= link_to events_path, class: 'hidden px-5 h-full lg:flex items-center hover:text-[#39364f]' do %>
      <span>Browse Events</span>
    <% end %>
    <%= link_to new_event_path, class: 'hidden px-5 h-full items-center hover:bg-gray-200 lg:flex text-[#3d64ff] ' do %>
      <span>Create an event</span>
    <% end %>
    <div class="hidden lg:flex h-full"><%= render partial: 'navbar/drop_down_organize', layout:'navbar/dropdown_layout', locals: { is_event_view: true} %></div>
    <div class="hidden lg:flex  h-full"><%= render partial: 'navbar/drop_down_help', layout:'navbar/dropdown_layout', locals: {is_event_view: true} %></div>
    <div class="lg:hidden flex  h-full"><%= render partial: 'navbar/drop_down_event', layout:'navbar/dropdown_layout', locals: { is_event_view: true} %></div>
    <%= render(partial: 'navbar/drop_down_user', layout: 'navbar/dropdown_layout', locals: { is_event_view: true}) if user_signed_in? %>
    <div class="[&>*:hover]:bg-gray-100 [&>*]:px-5 lg:flex h-full hidden"><%= render 'navbar/log_in_items' %></div>
  </ul>
</nav>

app/views/navbar/_navbar_user_layout_using.html.erb
  <% content_for :picture do %>
  <div class="flex items-center justify-center lg:bg-gray-100 rounded-full h-10 w-10">
    <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" >
      <path id="user-chunky_svg__eds-icon--user-chunky_base" fill-rule="evenodd" clip-rule="evenodd" d="M12 18c-1.2 0-2.4-.3-3.5-.7.6-1.3 2-2.2 3.5-2.2s2.9.9 3.5 2.2c-1.1.4-2.3.7-3.5.7zm6.5-2.9c-.4.4-.8.8-1.3 1.1a5.989 5.989 0 00-10.6 0c-.5-.3-.9-.7-1.3-1.1L4 16.5c2.1 2.3 5 3.5 8 3.5s5.9-1.3 8-3.5l-1.5-1.4z"></path><path id="user-chunky_svg__eds-icon--user-chunky_circle" fill-rule="evenodd" clip-rule="evenodd" d="M12 4C9.7 4 7.8 5.9 7.8 8.2s1.9 4.2 4.2 4.2 4.2-1.9 4.2-4.2S14.3 4 12 4zm0 6.4c-1.2 0-2.2-1-2.2-2.2C9.8 7 10.8 6 12 6s2.2 1 2.2 2.2c0 1.2-1 2.2-2.2 2.2z"></path>
    </svg>
  </div>
<% end %>
<% content_for :label do %>
  <span class="pl-2"><%= current_user.email %></span>
<% end %>
<% content_for :list do %>
  <li class="border-b-[1px] border-gray-100">
    <%= link_to 'Browse Events', root_path %>
  </li>
  <li><%= link_to 'Tickets (0)', not_implemented_path %></li>
  <li><%= link_to 'Credits', not_implemented_path %></li>
  <li><%= link_to 'Liked', not_implemented_path %></li>
  <li><%= link_to 'Following', not_implemented_path %></li>
  <li><%= link_to 'Interests', not_implemented_path %></li>
  <li class=" border-t-[1px] border-gray-100">
    <%= link_to 'Account Settings', edit_user_registration_path %>
  </li>
  <li>
    <div class="flex truncate text-[#a9a8b3] cursor-not-allowed">
      <%= current_user.email %>
    </div>
  </li>
  <li><%= link_to 'Log Out', destroy_user_session_path %></li>
  <li class="lg:hidden  border-t-[1px] border-gray-100">
    <%= link_to 'Organize', not_implemented_path %>
  </li>
  <li class="lg:hidden ">
    <%= link_to 'Help', not_implemented_path %>
  </li>
<% end %>

app/views/navbar/_search.html.erb
<%# TODO make this a proper modal %>
<div class="flex flex-grow">
  <%= link_to not_implemented_path,
  class: "hidden lg:flex flex-row flex-grow max-w-[472px] max-h-[46px] items-center bg-[#f8f7fa] py-[5px]" do %>
    <div class= 'flex items-center justify-center my-3 ml-3'>
      <%= inline_svg_tag 'svg/magnifying_glass.svg', class:'h-6 w-6', style: 'fill: #a9a8b3' %>
    </div>
    <span class='hidden lg:block bg-[#f8f7fa] border-none text-sm text-gray-600 font-light px-2 py-3'>Search events</span>
  <% end %>
</div>
<div class="ml-auto lg:hidden flex h-full text-[#6f7287]
<%= 'text-[#39364f] min-w-[72px] hover:bg-[#f8f7fa]' unless local_assigns[:is_event_view] %>">
  <%= form_with url: not_implemented_path,
  class: 'w-full h-full flex items-center justify-center text-current' do |f| %>
    <%= f.button (inline_svg_tag 'svg/magnifying_glass.svg', class:'h-6 w-6', fill: 'currentColor'), 'aria-label': 'Search'  %>
  <% end %>
</div>

app/views/navbar/_signed_in_items.html.erb
<div class="lg:flex h-full hidden
 [&>*]:px-5 [&>*]:h-full [&>*]:flex [&>*]:flex-col [&>*]:items-center [&>*:hover]:bg-[#f8f7fa] [&>*]:justify-center [&>*]:cursor-pointer">
  <%= link_to new_event_path, class: ' text-[#3d64ff] ' do %>
    <%= inline_svg_tag 'svg/plus.svg', class:'h-6 w-6' %>
    <span>Create an event</span>
  <% end %>
  <%= link_to not_implemented_path do %>
    <%= inline_svg_tag 'svg/heart.svg', class:'h-6 w-6', fill: 'currentColor' %>
    <span class="">Likes</span>
  <% end %>
  <%= link_to not_implemented_path do %>
    <%= inline_svg_tag 'svg/ticket.svg', class:'h-6 w-6' %>
    <span class="">Tickets</span>
  <% end %>
</div>
<%= render partial: 'navbar/drop_down_user', layout: 'navbar/dropdown_layout' %>

app/views/navbar/_signed_out_items.html.erb
<div class="hidden lg:block h-full"><%= render partial: 'navbar/drop_down_organize', layout:'navbar/dropdown_layout' %></div>
<div class="hidden lg:block h-full"><%= render partial: 'navbar/drop_down_help', layout:'navbar/dropdown_layout' %></div>
<%= link_to new_event_path, class: 'hidden px-5 h-full lg:flex items-center hover:bg-[#f8f7fa] text-[#3d64ff]' do %>
  <span>Create an event</span>
<% end %>
<div class="block lg:hidden h-full">
  <%= render partial: 'navbar/drop_down_dots', layout:'navbar/dropdown_layout' %>
</div>
<div class="[&>*:hover]:bg-gray-100 [&>*]:px-5 flex h-full"><%= render 'navbar/log_in_items' %></div>