config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    post 'users/sign_up' => 'users/registrations#create'
    get 'users/edit/update_password' => 'users/registrations#update_password'
    get 'users/edit/close_account' => 'users/registrations#close_account'
    post 'users/edit/close_account' => 'users/registrations#close_account_action'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'not_implemented', to: 'application#not_implemented'
  post 'not_implemented', to: 'application#not_implemented'

  resources :users, only: :show
  resources :events
  resources :user_event_permissions, only: :create
  delete 'user_event_permissions', to: 'user_event_permissions#destroy'

  root 'events#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :events_created, class_name: 'Event', foreign_key: 'creator_id',
                            dependent: :destroy, inverse_of: :creator

  has_many :user_event_permissions, dependent: :destroy
  has_many :event_relations, through: :user_event_permissions, source: :event

  # TODO: maybe this needs eager loading?
  has_many :events_attended_perms, -> { where permission_type: 'attend' },
           class_name: 'UserEventPermission', inverse_of: :user, dependent: false
  has_many :events_attended, through: :events_attended_perms, source: :event

  has_many :events_pending_perms, -> { where permission_type: 'accept_invite' },
           class_name: 'UserEventPermission', inverse_of: :user, dependent: false
  has_many :events_pending, through: :events_pending_perms, source: :event

  validates :name, presence: true, length: { in: 3..30 }
  validates :username, presence: true, length: { minimum: 5 }

  def attending?(event_id)
    holds_permission_currently?(event_id, 'attend')
  end

  def invite?(event_id)
    holds_permission_currently?(event_id, 'accept_invite')
  end

  def can_moderate?(event_id)
    holds_permission_currently?(event_id, 'moderate', 'owner')
  end

  def can_edit?(event_id)
    holds_permission_currently?(event_id, 'owner')
  end

  # returns an array of permissions that the current user holds
  # for the prospective permission being acted on
  # assumes event_id is valid
  def held_event_perms(event_id, current_user_id)
    perms = user_event_permissions.where(event_id:).pluck(:permission_type)
    perms << 'current_user' if id == current_user_id
    perms
  end

  private

  def holds_permission_currently?(event_id, *permission_type)
    user_event_permissions.where(event_id:, permission_type:).any?
  end
end

app/controllers/users/registrations_controller.rb
# rubocop:disable Metrics/AbcSize, Metrics/MethodLength, Rails/LexicallyScopedActionFilter
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  prepend_before_action :authenticate_scope!,
                        only: %i[update close_account close_account_action update_password edit]
  prepend_before_action :set_minimum_password_length, only: %i[update_password]

  # GET /resource/sign_up
  # def new
  #   render 'new', locals: { resource: User.new }
  #   super
  # end
  def close_account; end

  def close_account_action
    valid_params = sanitize_close_account_params
    resource = current_user
    if valid_params[:close] == 'CLOSE' && current_user.valid_password?(valid_params[:password])
      resource.destroy
      Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
      set_flash_message! :notice, :destroyed
      yield resource if block_given?
      respond_with_navigational(resource) { redirect_to after_sign_out_path_for(resource_name) }
    else
      redirect_to users_edit_close_account_path, alert: 'Invalid. Please try again.'
    end
  end

  def update_password; end

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length

      # respond_with resource
      if resource.errors[:email].empty?
        landing_on_valid_email_page resource
        render 'valid_email', locals: { resource: }
      else
        render 'new', locals: { resource: }
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)

    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      respond_with resource, location: edit_registration_path(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      if params[:user][:password_confirmation].present?
        render :update_password, locals: { resource: }
      else
        respond_with resource
      end
    end
  end

  # DELETE /resource
  def destroy; end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[email name username password password_confirmation])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def sanitize_params
    params.require(:user).permit(:email)
  end

  def sanitize_close_account_params
    params.permit(:password, :close)
  end

  def build_user
    User.new(sanitize_params)
  end

  def find_user
    @user = User.includes(events_created: [:creator]).find(params[:id])
  end

  def update_resource(resource, params)
    resource.update(params)
  end

  def landing_on_valid_email_page(resource)
    resource.errors.clear if params.require(:user).permit(:wizard_stage)['wizard_stage'] == '1'
  end
end

# rubocop:enable Metrics/AbcSize, Metrics/MethodLength, Rails/LexicallyScopedActionFilter

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: :show
  def show; end

  private

  def find_user
    @user = User.includes(events_created: [:creator]).find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_short_user.html.erb
<%= link_to resource do %>
  <div class="flex flex-row items-center">
    <div class="mr-2"><%= image_tag 'profile_picture_placeholder.png', size: '40x40', style: 'border-radius: 9999px', alt: 'User profile picture placeholder' %></div>
    <div class="flex flex-col text-sm">
      <div class="font-semibold clamp-one"><%= resource.name.titleize %></div>
      <div class="text-xs clamp-one"><%= resource.email %></div>
    </div>
  </div>
<% end %>

app/views/users/_short_user_alt.html.erb
<div class="flex flex-row items-center">
  <%= link_to resource do %>
    <div class="flex flex-col text-[#39364f]">
      <div class="font-semibold text-base clamp-two"><%= resource.username.titleize %> | <%= resource.name.titleize %></div>
      <div class="flex flex-row items-center">
        <%= inline_svg_tag 'svg/user_placeholder.svg', class: 'h-4 w-4' %>
        <div class="font-semibold text-base pl-2">3.4k followers</div>
      </div>
    </div>
  <% end %>
  <% if local_assigns[:show_share] %>
    <%= link_to not_implemented_path, class: 'cursor-pointer' do %>
      <%= inline_svg_tag 'svg/share.svg', class:'h-6 w-6' %>
    <% end %>
  <% end %>
</div>

app/views/users/_short_user_alt_two.html.erb
<div class="flex flex-row items-center my-2">
  <div class="flex flex-col text-[#39364f]">
    <div class="font-normal text-[15px] text-[#39364f] clamp-one">by <%= link_to resource.username.titleize, resource, class: 'text-blue-700 hover:underline' %></div>
    <div class="flex flex-row items-center">
      <div class="font-normal text-base pr-2 text-gray-400"><%= rand(9999) %> followers</div>
      <%= button_to not_implemented_path, class: 'border-[#3659e3] border-2 flex bg-white rounded px-2 h-6 items-center justify-center' do %>
        <span class="font-semibold text-xs text-[#3659e3]">Follow</span>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_sidebar.html.erb
<div class="flex flex-col bg-[#f8f7fa] w-full h-full">
  <div class="flex flex-col text-sm font-normal text-gray-600 relative" x-data="{open_submenu: false}">
    <button class="flex px-5 py-4 justify-between items-center hover:text-black" @click="open_submenu = ! open_submenu">
      <span class="font-semibold">Account</span>
      <div :class="open_submenu && 'rotate-180'"><%= render 'navbar/chevron_svg' %></div>
    </button>
    <ul class="relative flex flex-col [&>*]:min-h-[53px] [&>*:hover]:text-black [&>*]:w-72 [&>*]:py-4 [&>*]:pr-5 [&>*]:pl-9"
      x-show="open_submenu" x-cloak>
      <li><%= link_to 'Contact Info', edit_user_registration_path %></li>
      <li><%= link_to 'Password', users_edit_update_password_path %></li>
      <li>Credit/Debit Cards</li>
      <li>Email Preferences</li>
      <li>Linked Accounts</li>
      <li><%= link_to 'Close Account', users_edit_close_account_path %></li>
      <li>Personal Data</li>
    </ul>
  </div>
  <div class="flex flex-col text-sm font-normal text-gray-600 relative" x-data="{open_submenu: false}">
    <button class="flex px-5 py-4 justify-between items-center hover:text-black" @click="open_submenu = ! open_submenu">
      <span class="font-semibold">Developer Links</span>
      <div :class="open_submenu && 'rotate-180'"><%= render 'navbar/chevron_svg' %></div>
    </button>
    <ul class="relative flex flex-col [&>*]:min-h-[53px] [&>*:hover]:text-black [&>*]:w-72 [&>*]:py-4 [&>*]:pr-5 [&>*]:pl-9"
      x-show="open_submenu" x-cloak>
      <li>API Keys</li>
    </ul>
  </div>
</div>

app/views/users/_user.html.erb
<div class="w-full items-center flex flex-col" x-data x-intersect:enter="$store.user_in_view = true" x-intersect:leave="$store.user_in_view = false">
  <div class="h-[400px] md:h-[640px] w-full absolute overflow-hidden">
    <div class="absolute md:mt-[-10%] overflow-hidden right-0 left-0">
      <%= image_tag 'profile_picture_placeholder.png', alt: 'User profile picture placeholder', class: 'blur-lg h-[200%] w-[200%]' %>
    </div>
  </div>
  <div class="hidden md:flex flex-col text-center items-center bg-white z-10 w-[672px] shadow-2xl rounded my-16 py-16">
    <%= image_tag 'profile_picture_placeholder.png', alt: 'User profile picture placeholder', size: '200x200', style: 'border-radius: 9999px' %>
    <h1 class="py-4 text-5xl leading-[40px] font-extrabold"><%= user.username.titleize %></h1>
    <p class="font-normal text-sm text-[#6f7287]">Hosted <%= user.events_created.count %> events total</p>
    <p class="font-normal text-sm text-[#6f7287] pt-1"><%= rand(99999) %> followers</p>
    <div class="flex items-center justify-center mt-4 ml-4 h-11 border-2 border-[#3659e3] rounded-[4px] hover:bg-[#f8f7fa]">
      <span class="font-semibold text-sm px-8 pb-[1px] text-[#3659e3]">Follow</span>
    </div>
    <div class="pt-8 items-center">
      <div class="bg-[#f8f7fa] rounded-full hover:bg-gray-200 p-2">
        <%= inline_svg_tag 'svg/globe.svg', class: 'h-6 w-6' %>
      </div>
    </div>
    <div class="pt-8">
      <div class="flex justify-center items-center px-8 h-11 hover:bg-gray-200 rounded">
        <span class="text-[#3659e3] text-sm font-semibold">Contact the organizer</span>
      </div>
    </div>
  </div>
  <div class="flex flex-col self-end text-center items-center justify-center bg-white z-10 w-full rounded md:hidden relative mt-[400px]">
    <div class="flex absolute -top-12 "><%= image_tag 'profile_picture_placeholder.png', alt: 'User profile picture placeholder', size:'96x96', style: 'border-radius: 9999px' %></div>
    <h1 class="pt-20 pb-4 text-3xl leading-[40px] font-extrabold"><%= user.username.titleize %></h1>
    <p class="font-normal text-sm text-[#6f7287]">Hosted <%= user.events_created.count %> events total</p>
    <p class="font-normal text-sm text-[#6f7287] pt-1"><%= rand(99999) %> followers</p>
    <div class="flex items-center justify-center mt-4 ml-4 h-11 border-2 border-[#3659e3] rounded-[4px] hover:bg-[#f8f7fa]">
      <span class="font-semibold text-sm px-8 pb-[1px] text-[#3659e3]">Follow</span>
    </div>
  </div>
</div>
<nav class="w-full flex font-semibold text-base px-4" x-data x-show="$store.user_in_view">
  <%= render 'users/user_sections' %>
</nav>
<nav class="fixed top-0 bg-white z-30 w-full flex flex-col font-semibold text-base px-4 shadow-lg" x-data x-cloak x-show="! $store.user_in_view">
  <div class="pt-2 pb-3 md:pt-8 md:pb-4 flex justify-between items-center">
    <h1 class="text-xl font-semibold md:text-3xl md:leading-[40px] md:font-bold"><%= user.username.titleize %></h1>
    <div class="flex items-center justify-center mt-4 ml-4 h-6 md:h-11 border-2 border-[#3659e3] rounded-[4px] hover:bg-[#f8f7fa]">
      <span class="font-semibold text-xs md:text-sm px-2 md:px-8 pb-[1px] text-[#3659e3]">Follow</span>
    </div>
  </div>
  <%= render 'users/user_sections' %>
</nav>

app/views/users/_user_sections.html.erb
<div class="[&>*]:pb-4 [&>*]:mr-6 flex border-b border-b-[#eeedf2] w-full text-gray-500" x-data>
  <%= link_to 'About', user_path(@user.id, anchor: 'about'), class: "border-b-2 border-b-current w-fit md:hidden", '@click': "$store.scroll_location = 'about'", ':class': "$store.scroll_location == 'about' && 'text-[#3d64ff]'"  %>
  <%= link_to 'Events', user_path(@user.id, anchor: 'events'), class: "border-b-2 border-b-current w-fit", ':class': "$store.scroll_location == 'events' && 'text-[#3d64ff]'", '@click': "$store.scroll_location = 'events'" %>
</div>

app/views/users/show.html.erb
<script>
  document.addEventListener('alpine:init', () => {
    Alpine.store('user_in_view', true)
      })
  document.addEventListener('alpine:init', () => {
    Alpine.store('scroll_location', false)
      })
</script>
<div class="flex items-center flex-grow">
  <div class="bg-white flex flex-col h-full flex-grow">
    <div class="">
      <%= render @user %>
    </div>
    <div id="about" class="md:hidden">
      <span class="" x-data x-intersect:enter="$store.scroll_location = 'about'"></span>
      <div class="pt-8 flex justify-center">
        <div class="bg-[#f8f7fa] rounded-full hover:bg-gray-200 p-2">
          <%= inline_svg_tag 'svg/globe.svg', class: 'h-6 w-6' %>
        </div>
      </div>
      <div class="pb-16 pt-8 flex justify-center items-center">
        <div class="flex items-center px-8 h-11 hover:bg-gray-200 rounded w-fit">
          <span class="text-[#3659e3] text-sm font-semibold">Contact the organizer</span>
        </div>
      </div>
    </div>
    <div class="flex flex-col py-8 px-8" x-data="{ time_filter: 'future' }">
      <h2 id="events" class="pb-3 text-3xl leading-[40px] font-bold" x-data x-intersect:enter="$store.scroll_location = 'events'">
        <%= @user.username.titleize %></h2>
      <div class="flex pb-8" >
        <button class="rounded-full mr-1 py-2 px-4 h-[44px] border-2 border-[#a9a8b3]" @click="time_filter = 'future'"
        :class="time_filter == 'future' && 'bg-[#3150cc] text-white border-none'">
          <span class="font-semibold">Upcoming (<%= @user.events_created.future.count %>)</span>
        </button>
        <button class="rounded-full mr-1 py-2 px-4 border-2 h-[44px] border-[#a9a8b3]" @click="time_filter = 'past'"
        :class="time_filter == 'past' && 'bg-[#3150cc] text-white border-none'">
          <span class="font-semibold">Past (<%= @user.events_created.past.count %>)</span>
        </button>
      </div>
      <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 justify-items-center"
       x-show="time_filter == 'future'" id="future-events">
        <%= render partial: 'events/event', collection: @user.events_created.future.limit(12), locals: {is_event_view: true, show_share: true } %>
      </div>
      <div class="grid gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 justify-items-center"
       x-show="time_filter == 'past'" id="past-events">
        <%= render partial: 'events/event', collection: @user.events_created.past.limit(12), locals: {is_event_view: true, show_share: true} %>
      </div>
    </div>
  </div>
</div>
<% content_for :footer do %>
  <%= render 'footer/footer_extended' %>
<% end %>
<% content_for :nav_bar do %>
  <%= render 'navbar/navbar_event' %>
<% end %>