config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    post 'users/sign_up' => 'users/registrations#create'
    get 'users/edit/update_password' => 'users/registrations#update_password'
    get 'users/edit/close_account' => 'users/registrations#close_account'
    post 'users/edit/close_account' => 'users/registrations#close_account_action'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'not_implemented', to: 'application#not_implemented'
  post 'not_implemented', to: 'application#not_implemented'

  resources :users, only: :show
  resources :events
  resources :user_event_permissions, only: :create
  delete 'user_event_permissions', to: 'user_event_permissions#destroy'

  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  AVAILIABLE_SETTINGS = %w[private protected public].freeze
  # maybe include some sort of proc to indicate wether user needs
  # all or any of the required perms to perform action
  belongs_to :creator, class_name: 'User'

  has_many :user_event_permissions, dependent: :destroy
  has_many :user_relations, through: :user_event_permissions, source: :user

  has_many :accepted_invites, -> { where(permission_type: 'attend') },
           class_name: 'UserEventPermission', inverse_of: :event, dependent: false
  has_many :attending_users, through: :accepted_invites, source: :user

  has_many :pending_invites, -> { where(permission_type: 'accept_invite') },
           class_name: 'UserEventPermission', inverse_of: :event, dependent: false
  has_many :pending_users, through: :pending_invites, source: :user

  validates :date, presence: true
  validates :location, presence: true
  validates :name, presence: true
  validates :desc, presence: true
  validates :event_privacy, inclusion: { in: AVAILIABLE_SETTINGS }
  validates :display_privacy, inclusion: AVAILIABLE_SETTINGS

  scope :past, -> { where('date <= ?', DateTime.now) }
  scope :future, -> { where('date > ?', DateTime.now) }

  after_commit :make_owner_permission, on: :create

  def self.display_public
    where(display_privacy: 'public')
  end

  def future?
    date > DateTime.now
  end

  def past?
    date <= DateTime.now
  end

  # Should be overwitten in the future
  def price
    'Free'
  end

  def image_url
    'https://img.evbuc.com/https%3A%2F%2Fcdn.evbuc.com%2Fimages%2F219765149%2F291099437342%2F1%2Foriginal.20220128-010041?w=512&auto=format%2Ccompress&q=75&sharp=10&rect=0%2C268%2C2048%2C1024&s=6e4df73b75bfc346275a65aaf2835680'
  end

  def accepted_invites
    user_event_permissions.where(permission_type: 'attend').includes(:user)
  end

  def pending_invites
    user_event_permissions.where(permission_type: 'accept_invite').includes(:user)
  end

  def viewable_by?(user)
    return true if display_privacy == 'public'
    return true if user && display_privacy == 'protected'

    holds_permission_currently?(user&.id, 'attend', 'moderate', 'owner', 'accept_invite')
  end

  def editable_by?(user)
    holds_permission_currently?(user&.id, 'owner')
  end

  def required_perms_for_action(perm_type:, action:)
    required_permissions.dig(action,
                             perm_type) || (raise "Invalid perm type: #{perm_type} or action: #{action}")
  end

  private

  def required_permissions
    attend_perm = event_privacy == 'private' ? %w[accept_invite current_user] : ['current_user']
    {
      create: {
        'moderate' => [['owner']],
        'attend' => [attend_perm],
        'accept_invite' => [['moderate'], ['owner']]
      },
      destroy: {
        'moderate' => [['owner']],
        'attend' => [['current_user'], ['moderate'], ['owner']],
        'accept_invite' => [['moderate'], ['owner']]
      }
    }.freeze
  end

  def holds_permission_currently?(user_id, *permission_type)
    user_event_permissions.where(user_id:, permission_type:).any?
  end

  ###################################################################
  ######################### Setup Tasks #############################
  ###################################################################
  def make_owner_permission
    user_event_permissions.create(user_id: creator_id, permission_type: 'owner')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_event, only: %i[show edit destroy update]
  before_action :build_event, only: %i[new create]
  before_action :perms_show?, only: :show
  before_action :perms_edit?, only: %i[edit update destroy]

  def index
    @events = Event.includes(:creator).all
  end

  def show; end

  def edit
    render 'new', locals: { resource: @event, action: :put }
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event updated!'
    else
      render 'new', locals: { resource: @event, action: :put }, status: :unprocessable_entity
    end
  end

  def new
    render 'new', locals: { action: :post }
  end

  def create
    if @event.update(event_params)
      redirect_to @event, notice: 'Event created!'
    else
      render 'new', locals: { action: :post }, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, notice: 'Event deleted.'
  end

  private

  def find_event
    @event = Event.includes(creator: [:events_created]).find(params[:id])
  end

  def event_params
    params.require(:event).permit(:date, :location, :event_privacy, :desc, :name, :display_privacy)
  end

  def perms_show?
    unless @event.viewable_by?(current_user)

      redirect_to(root_path, alert: 'You do not have permission to view that page.')
    end
  end

  def perms_edit?
    unless @event.editable_by?(current_user)
      redirect_to(root_path, alert: 'You do not have permission to edit that page.')
    end
  end

  # what is this here for?
  def build_event
    @event = current_user.events_created.build
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def render_with_display_perms(event)
    render 'event', resource: event if event.viewable_by?(current_user)
  end

  def render_event_rand_size(event)
    if rand(30) > 5
      render partial: 'events/event_small', locals: { resource: event }
    else
      render partial: 'events/event', locals: { event: }
    end
  end
end

app/views/events/_demo_layout.html.erb
<div x-data="radio_group" 
  @keydown.down.stop.prevent="selectNext" 
  @keydown.right.stop.prevent="selectNext" 
  @keydown.up.stop.prevent="selectPrevious" 
  @keydown.left.stop.prevent="selectPrevious" 
  role="radiogroup" 
  x-id="['radio-group-label']"
  class="relative"
  >
  <label :id="$id('radio-group-label')" role="none" class="hidden">Backend framework: <span x-text="value"></span></label>
  <%= content_for :radio_buttons %>
  <div class="bottom-0">
    <%= content_for :descriptions %>
  </div>
</div>
<script>
  document.addEventListener("alpine:init", () => {
    Alpine.data("radio_group", () => ({
      value: null,
      select(option) {
        this.value = option;
      },
      isSelected(option) {
        return this.value === option;
      },
      hasRovingTabindex(option, el) {
        if (
          this.value === null &&
          Array.from(el.parentElement.children).indexOf(el) === 0
        )
          return true;
        return this.isSelected(option);
      },
      selectNext(e) {
        let el = e.target;
        let siblings = Array.from(el.parentElement.children);
        let index = siblings.indexOf(el);
        let next = siblings[index === siblings.length - 1 ? 0 : index + 1];
        next.click();
        next.focus();
      },
      selectPrevious(e) {
        let el = e.target;
        let siblings = Array.from(el.parentElement.children);
        let index = siblings.indexOf(el);
        let previous = siblings[index === 0 ? siblings.length - 1 : index - 1];
        previous.click();
        previous.focus();
      },
    }));

    Alpine.bind("radio_option", (thing) => ({
      ["x-data"]() {
        return { option: thing };
      },
      ["@click"]() {
        return this.select(this.option);
      },
      ["@keydown.enter.stop.prevent"]() {
        return this.select(this.option);
      },
      ["@keydown.space.stop.prevent"]() {
        return this.select(this.option);
      },
      [":checked"]() {
        return this.isSelected(this.option);
      },
      [":tabindex"]() {
        return this.hasRovingTabindex(this.option, this.$el) ? 0 : -1;
      },
      [":aria-labelledby"]() {
        return this.$id("radio-option-label");
      },
      [":aria-describedby"]() {
        return this.$id("radio-option-description");
      },
      ["x-id"]() {
        return ["radio-option-label", "radio-option-description"];
      },
    }));
  });
</script>

app/views/events/_event_form.html.erb
<%= form_with model: resource, data: {turbo: false}, method: method, class: 'flex flex-col pb-16 gap-4 max-w-lg w-full' do |form| %>
  <%= form.text_field :name, placeholder: 'Enter a name for the event...', class: 'px-3 py-2 border border-gray-300 focus:border-red-300 focus:putline-none focus:ring focus:ring-red-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 block w-full'%>
  <%= render 'inline_errors', errors: resource.errors[:name] %>
  <%= form.text_field :desc, placeholder: 'Describe the event...', class: 'px-3 py-2 border border-gray-300 focus:border-red-300 focus:putline-none focus:ring focus:ring-red-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 block w-full' %>
  <%= render 'inline_errors', errors: resource.errors[:desc] %>
  <%= form.text_field :location, placeholder: 'Enter a location...', class: 'px-3 py-2 border border-gray-300 focus:border-red-300 focus:putline-none focus:ring focus:ring-red-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 block w-full' %>
  <%= render 'inline_errors', errors: resource.errors[:location] %>
  <%= form.datetime_local_field :date, class: 'px-3 py-2 border border-gray-300 focus:border-red-300 focus:putline-none focus:ring focus:ring-red-200 focus:ring-opacity-50 rounded-md shadow-sm disabled:bg-gray-100 block w-full' %>
  <%= render 'inline_errors', errors: resource.errors[:date] %>
  <div class="flex flex-col bg-gray-100 p-4 mt-6">
    <%= render 'radio_buttons_event_privacy', form: form %>
    <%= render 'radio_buttons_display_privacy', form: form %>
  </div>
  <%= form.submit 'Submit', class: 'w-full inline-flex items-center justify-center px-4 py-2 bg-red-600 border border-transparent rounded-md font-bold text-white capitalize transition disabled:opacity-25 focus:outline-none hover:bg-red-700 active:bg-red-700 focus:border-red-700 focus:ring focus:ring-red'%>
<% end %>

app/views/events/_event_mod_tools.html.erb
<div class="bg-yellow-300 p-8">
  <div class="font-extrabold text-2xl">Moderator Tools</div>
  <div class="flex flex-row w-full justify-evenly py-8">
    <%= link_to 'Edit Event', [:edit, resource], class: 'bg-green-400 rounded-md py-4 text-center w-full' %>
    <div class="w-full ml-8">
      <%= button_to 'Delete Event', resource, method: :delete, class: 'bg-red-500 rounded-md py-4 w-full text-center' %>
    </div>
  </div>
  <%= render 'user_event_permissions/create_invite_form', resource: resource %>
</div>

app/views/events/_full_event.html.erb
<div class="flex flex-col md:grid grid-cols-3 w-full" x-data x-intersect:enter="$store.user_in_view = true" x-intersect:leave="$store.user_in_view = false">
  <% if user_signed_in? && resource.editable_by?(current_user) %>
    <div class="flex grow col-start-1 col-end-4 bg-yellow-400 p-4 items-center">
      <div class="px-4"><%= inline_svg_tag 'svg/pencil.svg', class: 'h-10 w-10' %></div>
      <%= link_to 'You are the event owner. Click to switch to edit view.', edit_event_path(resource), class: 'hover:underline'  %>
    </div>
  <% end %>
  <div class="w-full col-span-2 relative ">
    <%= image_tag resource.image_url, class: 'w-full', alt: 'Event header image placeholder' %>
    <div class="md:hidden"><%= render 'user_event_permissions/heart_perm_button', resource: resource %></div>
  </div>
  <div class="hidden md:flex flex-col pb-5 px-[30px] pt-[30px] w-full bg-[#eeedef] justify-between relative">
    <div class="flex flex-col">
      <div class="flex flex-col text-[#39364f] absolute">
        <span class="text-[13px] font-semibold leading-4"><%= resource.date.strftime("%b").upcase %></span>
        <span class="text-[17px] font-normal leading-5"><%= resource.date.strftime("%e") %></span>
      </div>
      <div class=" pt-16 pb-[2px]">
        <h1 class="text-[#1e0a3c] text-base lg:text-xl font-semibold  clamp-four leading-5 max-h-32">
          <%= resource.name.titleize %>
        </h1>
      </div>
      <div class="py-2"><%= render "users/short_user_alt_two", resource: resource.creator %></div>
    </div>
    <div class="flex" x-data x-show="$store.user_in_view">
      <span>
        <%= resource.price %>
      </span>
    </div>
  </div>
  <div class="flex flex-col h-full w-full md:hidden relative px-4 pt-6 border-b border-b-[#dbdae3]">
    <div class="absolute sm:flex flex-col hidden">
      <span class="font-semibold text-sm"><%= resource.date.strftime("%^b") %></span>
      <span class="text-lg font-normal"><%= resource.date.strftime("%e") %></span>
    </div>
    <div class="flex flex-col sm:ml-16 ">
      <div class="font-bold text-xl max-h-32 clamp-four"><%= resource.name.titleize %></div>
      <div class="pt-1">
        <%= render "users/short_user_alt_two", resource: resource.creator %>
      </div>
    </div>
  </div>
</div>

app/views/events/_generic_radio_group.html.erb
<div x-data="{setting_description: '<%= resource.send(group_value) || 'public' %>'}">
  <div class="flex text-sm font-normal [&>*]:mr-4 [&>*]:flex-grow mb-1 w-full">
    <% radio_buttons.map { |v| v[:val] }.each do |value| %>
      <%= render partial: 'events/generic_radio_button', locals: {group_value: , value:, form:, resource:} %>
    <% end %>
  </div>
  <div class="bottom-0">
    <%= render 'inline_errors', errors: resource.errors[group_value] %>
    <% radio_buttons.each do |button| %>
      <p class="font-normal text-sm break-normal leading-6" x-show="setting_description == '<%= button[:val] %>'"><%= button[:desc] %></p>
    <% end %>
  </div>
</div>

app/views/events/_listing_map.html.erb
<div class="flex flex-col pb-5">
  <div class="pb-5"><%= image_tag 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/World_map_blank_without_borders.svg/1024px-World_map_blank_without_borders.svg.png',
  alt: 'Google maps placeholder image' %></div>
  <div class="flex flex-col items-center">
    <div class="flex flex-col py-5 items-center text-[#1e0a3c] font-semibold text-xl max-w-3xl text-center">
      <span><%= @event.name.titleize %></span>
      <span class="py-2 text-[#39364f] text-base font-normal">at</span>
      <span class="pb-1">Location Name Placeholder</span>
      <span class="pt-1 text-[#39364f] text-base font-normal"><%= @event.location.titleize %></span>
    </div>
    <ul class="flex  [&>*]:flex [&>*]:items-center [&>*]:justify-center  [&>*]:rounded-full [&>*]:border-transparent [&>*]:border-2">
      <li class="hover:bg-[#f8f7fa] hover:border-[#f8f7fa]">
        <%= button_to not_implemented_path, class: 'p-[10px]', 'aria-label': 'Car Route' do %>
          <%= inline_svg_tag 'svg/car.svg', class:'h-6 w-6' %>
        <% end %>
      </li>
      <li class="hover:bg-[#f8f7fa] hover:border-[#f8f7fa]">
        <%= button_to not_implemented_path, class: 'p-[10px]', 'aria-label': 'Pedestrian Route' do %>
          <%= inline_svg_tag 'svg/pedestrian.svg', class:'h-6 w-6' %>
        <% end %>
      </li>
      <li class="hover:bg-[#f8f7fa] hover:border-[#f8f7fa]">
        <%= button_to not_implemented_path, class: 'p-[10px]', 'aria-label': 'Bus Route' do %>
          <%= inline_svg_tag 'svg/bus.svg', class:'h-6 w-6' %>
        <% end %>
      </li>
      <li class="hover:bg-[#f8f7fa] hover:border-[#f8f7fa]">
        <%= button_to not_implemented_path, class: 'p-[10px]', 'aria-label': 'Biking Route' do %>
          <%= inline_svg_tag 'svg/bike.svg', class:'h-6 w-6' %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/events/_new_basic_info.html.erb
<div class="mt-5 pb-12 mb-12 pt-5 flex flex-col lg:grid grid-cols-12 px-4 lg:px-0">
  <div class="col-start-2 hidden lg:block"><%= inline_svg_tag 'svg/text.svg', class:'h-12 w-12 text-[#dbdae3]' %></div>
  <div class="flex flex-col col-start-3 col-span-8">
    <h1 class="text-3xl font-bold">Basic Info</h1>
    <p class="font-normal text-sm break-normal">Name your event and tell event-goers why they should come. Add details that highlight what makes it unique.</p>
    <div class="flex flex-col">
      <div class="pb-6 relative">
        <%= render partial: 'fields/text_field_labeled', locals: { resource: @event, form:, field_name: :name, placeholder: 'Be clear and descriptive.', value: 'Event Title', hidden: false } %>
        <span class="absolute bottom-0 right-0 text-sm ">0/75</span>
      </div>
      <div class="mb-2"><%= render partial: 'fields/text_field_labeled', locals: { resource: @event, form:, field_name: :desc, placeholder: 'Describe the event and organizer.', value: 'Description', hidden: false } %></div>
      <p class="ont-normal text-xs break-normal">This profile describes a unique organizer and shows all of the events on one page.
        <span class="text-blue-700 hover:underline">View Organizer Info</span>
      </p>
      <div class="flex flex-col md:grid grid-cols-3 gap-4 mt-8">
        <%= form.select :type, [['Select a type', ''], ['Placeholder', 'Placeholder'],['Placeholder', 'Placeholder'], ['Type', 'Type']], selected: 'Type' %>
        <%= form.label :type, 'Placeholder Type', class: 'sr-only' %>
        <%= form.select :category, [['Category', nil],['Placeholder',nil],['Placeholder',nil]] %>
        <%= form.label :category, 'Category Type', class: 'sr-only' %>
      </div>
      <div class="flex flex-col pt-4">
        <span class="text-lg font-semibold mb-2">Tags</span>
        <p class="mb-4 text-sm font-normal">Improve discoverability of your event by adding tags relevant to the subject matter.</p>
        <div class="flex">
          <div class="flex flex-col mb-4 pr-2 w-full">
            <%= render partial: 'fields/text_field_labeled', locals: {
                             resource: @event, form:, field_name: :tags, 
                             placeholder: 'Add search keywords to your event', 
                             value: 'Press Enter to add a tag', hidden: false } %>
            <div class="flex justify-between font-normal text-xs pt-1"><span>0/10 tags.</span><span>0/25</span></div>
          </div>
          <%= form.submit 'Add', class: 'border-2 border-[#a9a8b3] hover:border-[#6f7287] hover:bg-[#f8f7fa] h-[44px] px-8 rounded mt-2' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_placeholder_text.erb
  
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed adipiscing diam donec adipiscing tristique risus nec. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Amet aliquam id diam maecenas ultricies mi eget.</p>
<br>
<p>Justo nec ultrices dui sapien eget mi. Rhoncus est pellentesque elit ullamcorper dignissim cras. Mauris augue neque gravida in. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Vitae ultricies leo integer malesuada nunc vel risus commodo.</p>
<br>
<p>Massa sapien faucibus et molestie. Vel orci porta non pulvinar neque laoreet. Ornare suspendisse sed nisi lacus sed viverra. Ultricies tristique nulla aliquet enim. Tortor id aliquet lectus proin nibh nisl condimentum.</p>
<br>
<p>Ac placerat vestibulum lectus mauris. Adipiscing at in tellus integer feugiat scelerisque varius morbi enim. Purus in mollis nunc sed id semper risus in. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in.</p>

app/views/events/_potential_participant_listing.erb
<div class="mt-5 pt-5 pb-20 flex flex-col lg:grid grid-cols-12 px-4 lg:px-0 w-full">
  <div class="col-start-2 hidden lg:block"><%= inline_svg_tag 'svg/text.svg', class:'h-12 w-12 text-[#dbdae3]' %></div>
  <div class="flex flex-col col-start-3 col-span-8">
    <h2 class="text-3xl font-bold">Invites</h1>
    <p class="font-normal text-sm break-normal leading-6 mb-6">Invite additional users to this event, or manage users already attending.</p>
    <%= render 'user_event_permissions/create_invite_form', resource: resource %>
    <div class="flex w-full mt-5 gap-8">
      <div class="flex flex-col w-full grow">
        <h3 class="text-lg font-semibold mb-2">Attending Users</h3>
        <div class="flex flex-col py-2 gap-y-4" id="accepted-invites">
          <% resource.accepted_invites.limit(10).each do |attendee| %>
            <%= render 'user_event_permissions/short_permission', resource: attendee %>
          <% end %>
        </div>
      </div>
      <div class="flex flex-col w-full grow">
        <h3 class="text-lg font-semibold mb-2">Pending Invites</h3>
        <div class="flex flex-col py-2 gap-y-4" id="pending-invites" >
          <% resource.pending_invites.limit(10).each do |pending| %>
            <%= render 'user_event_permissions/short_permission', resource: pending %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_sidebar_label.html.erb
<span class="fixed left-16 border hidden shadow-lg  group-hover:block bg-white text-black px-4 py-2 text-sm font-normal z-999"><%= text %></span>

app/views/events/_tag.html.erb
<%= link_to not_implemented_path, class: 'cursor-pointer border-2 border-[#eeedf2] font-normal hover:bg-gray-100 bg-white text-sm text-[#39364f] rounded-full h-9 px-4 mt-4 mr-4 flex items-center min-w-fit' do %>
  <span><%= tag_text %></span>
<% end %>

app/views/events/_test.html.erb
  <%= form.label :date, 'start time' %>
<%= form.time_field :date, value: Time.now.strftime("%H:%M"), 
    class: 'flex border-[1px] border-[#dbdae3] rounded-sm w-full items-center h-[48px] text-sm p-[0px]' do |f| %>
  <span class="text-[#6f7287] text-xs">Start Time</span>
</div>
<% end %>

app/views/events/index.html.erb
<div class="w-full h-full flex flex-col items-center">
  <%= render 'header_image'%>
  <div class="flex flex-col max-w-7xl px-4 items-center w-full">
    <%= render 'nonfunctional/location_search_form' %>
    <%= render 'nonfunctional/event_filters' %>
    <%= render 'nonfunctional/event_categories' %>
    <div class="flex flex-col py-10">
      <div class="text-black font-bold text-2xl px-3 pb-6">Events in Four Corners</div>
      <div class="grid grid-cols-1  sm:grid-cols-2  md:grid-cols-3 xl:grid-cols-4 justify-center items-center">
        <%= render @events.future.limit(2) %>
        <%= render 'nonfunctional/event_card_filler' %>
      </div>
    </div>
    <div class="bg-[#f8f7fa] max-w-full">
      <%= render 'nonfunctional/personal_filters' %>
    </div>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 grid-rows-2 justify-items-center">
      <%= render @events.future.limit(8) %>
    </div>
    <div class="bg-[#f8f7fa] max-w-full">
      <%= render partial: 'nonfunctional/collections', layout: 'layouts/carousel_layout' %>
    </div>
    <div class="flex flex-col pt-10">
      <div class="text-black font-bold text-2xl px-3 mb-6">More Events</div>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 justify-items-center">
        <%= render @events.future.limit(12) %>
      </div>
    </div>
  </div>
  <%= render 'nonfunctional/see_more' %>
</div>
<% content_for :footer do %>
  <%= render 'footer/footer_extended' %>
<% end %>
<% content_for :nav_bar do %>
  <%= render 'navbar/navbar' %>
<% end %>

app/views/events/show.html.erb
<script>
  document.addEventListener('alpine:init', () => {
    Alpine.store('user_in_view', true)
      })
</script>
<div class="flex flex-col h-full w-full items-center bg-[#f8f7fa] relative lg:pt-10">
  <div class="w-full top-0 hidden lg:block absolute h-[470px] overflow-hidden">
    <%= image_tag @event.image_url, size: '50x25', class: 'w-[200%] filter', style: "filter: blur(50px)", alt: 'Event background placeholder' %>
  </div>
  <div class="bg-white flex flex-col w-full md:max-w-5xl items-center rounded-t shadow-sm lg:z-10">
    <%= render 'full_event', resource: @event %>
    <%= render 'sticky_navbar', resource: @event %>
    <div class="px-2 pb-5">
      <div class="sm:grid grid-cols-12 pt-12 pb-10 hidden">
        <div class="flex flex-col col-start-2 col-end-8 pl-1">
          <span class="font-normal text-base text-[#39364f] mb-8"><b><%= @event.name.titleize %></b></span>
          <div class="flex flex-col">
            <h2 class="font-semibold text-xl mb-5">About this event</h2>
            <div class="text-[15px] text-[#6f7287]"><%= @event.desc %></div>
            <div class="mt-12"><%= render 'tags' %></div>
            <div class="mt-12"><%= render 'share' %></div>
          </div>
        </div>
        <div class="col-start-9 col-end-13 pr-1 flex flex-col">
          <div class="mb-12"><%= render 'date_time', resource: @event %></div>
          <div class="mb-12"><%= render 'location', resource: @event %></div>
          <div class="mb-12"><%= render 'refund_policy' %></div>
        </div>
      </div>
      <div class="flex flex-col pt-6 pb-10 sm:hidden" >
        <div class="mb-12"><%= render 'date_time', resource: @event %></div>
        <div class="mb-12"><%= render 'location', resource: @event %></div>
        <div class="mb-12"><%= render 'refund_policy' %></div>
        <span class="font-normal text-base text-[#39364f] mb-8"><b><%= @event.name.titleize %></b></span>
        <div class="flex flex-col">
          <h2 class="font-semibold text-xl mb-5">About this event</h2>
          <div class="text-[15px] text-[#6f7287]"><%= render 'placeholder_text' %></div>
          <div class="mt-12"><%= render 'tags' %></div>
          <div class="mt-12"><%= render 'share' %></div>
        </div>
      </div>
    </div>
    <%= render 'listing_map', resource: @event %>
    <%= render 'organizer_listing', resource: @event %>
    <%# render 'mod_tools', resource: @event %>
    <%# render 'events/potential_participant_listing', resource: @event %>
    <div class="bg-[#f8f7fa] flex w-full"><%= render partial: 'events/event_carousel', layout: 'layouts/carousel_layout', resource: @event %></div>
  </div>
</div>
<% content_for :footer do %>
  <%= render 'footer/footer_short' %>
<% end %>
<% content_for :nav_bar do %>
  <%= render 'navbar/navbar_event' %>
<% end %>