config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    post 'users/sign_up' => 'users/registrations#create'
    get 'users/edit/update_password' => 'users/registrations#update_password'
    get 'users/edit/close_account' => 'users/registrations#close_account'
    post 'users/edit/close_account' => 'users/registrations#close_account_action'
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get 'not_implemented', to: 'application#not_implemented'
  post 'not_implemented', to: 'application#not_implemented'

  resources :users, only: :show
  resources :events
  resources :user_event_permissions, only: :create
  delete 'user_event_permissions', to: 'user_event_permissions#destroy'

  root 'events#index'
end

app/views/layouts/_carousel_layout.html.erb
<div class="flex flex-col px-6 pt-16 pb-16 w-full md:max-w-5xl items-center" x-data="carousel">
  <div class="flex items-center justify-between w-full">
    <%= content_for :carousel_title  %>
    <div class="flex flex-row text-black">
      <%#TODO acessibility stuff%>
      <div id="leftArrow" x-on:click="pageLeft">
        <%= content_for :left_arrow %>
      </div>
      <div id="rightArrow" x-on:click="pageRight">
        <%= content_for :right_arrow %>
      </div>
    </div>
  </div>
  <ul id="slider" class="flex overflow-x-scroll snap-x snap-mandatory w-full" x-ref="carouselBody">
    <%= yield %>
  </ul>
</div>
<script>
  document.addEventListener('alpine:init', () => {
    Alpine.data('carousel', () => ({

      numCarouselCols() {
        let carouselBody = this.$refs.carouselBody
        let parentWidth = carouselBody.getBoundingClientRect().width
        let childWidth = carouselBody.firstElementChild.getBoundingClientRect().width
        return Math.floor(parentWidth / childWidth)
      },
      pageRight() { this.destLocation((currentLoc, elementWidth) => currentLoc +
      ( elementWidth * this.numCarouselCols() )) },
      pageLeft() { this.destLocation((currentLoc, elementWidth) => currentLoc -
      ( elementWidth * this.numCarouselCols() )) },

      destLocation(scrollFunc) {
        let carouselBody = this.$refs.carouselBody
        let currentLoc = carouselBody.scrollLeft
        let elementWidth = carouselBody.firstElementChild.getBoundingClientRect().width
        carouselBody.scrollTo({ left: scrollFunc(currentLoc, elementWidth), behavior: 'smooth' })
      }
    }))
  })
  let parent = document.getElementById('slider')
  let leftArrow = document.getElementById('leftArrow').firstElementChild
  leftArrow.setAttribute('disabled', true)
  let rightArrow = document.getElementById('rightArrow').firstElementChild
  parent.addEventListener('scroll', () => {
    parent.scrollLeft == 0 ? leftArrow.setAttribute('disabled', true) : leftArrow.removeAttribute('disabled')
    parent.scrollLeft == parent.scrollLeftMax ? rightArrow.setAttribute('disabled', true) : rightArrow.removeAttribute('disabled')

  })
</script>

app/views/layouts/_generic_attend_perm_button.html.erb
<%= form_with url: user_event_permissions_url, scope: :user_event_permissions, method: method, data: { turbo: 'false' } do |form| %>
  <%= form.hidden_field :event_id, value: resource.id %>
  <%= form.hidden_field :permission_type, value: 'attend' %>
  <%= yield form %>
<% end %>

app/views/layouts/_generic_perm_button.html.erb
<%= form_with url: user_event_permissions_url, scope: :user_event_permissions, method: method do |form| %>
  <%= form.hidden_field :event_id, value: resource.id %>
  <%= form.hidden_field :permission_type, value: 'attend' %>
  <%= yield form %>
<% end %>

app/views/layouts/_registration_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name),
 data: {turbo: false}, method: method) do |form| %>
  <%= yield form %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script defer src="https://unpkg.com/@alpinejs/intersect@3.x.x/dist/cdn.min.js"></script>
    <script defer src="https://unpkg.com/alpinejs@3.10.3/dist/cdn.min.js"></script>
  </head>
  <body class="w-full flex flex-col min-h-screen">
    <%= yield :nav_bar %>
    <%= render 'notices' %>
    <div class="flex w-full">
      <%= yield :side_bar %>
      <div class="flex flex-col w-full">
        <main class="w-full flex min-h-screen">
          <%= yield %>
        </main>
        <%= yield :footer %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login_layout.html.erb
<% content_for :content do %>
  <%= render 'notices' %>
  <main class="h-full min-h-screen w-full flex flex-col bg-white">
    <%= yield %>
  </main>
  <%= render 'footer/footer_extended' %>
<% end %>
<%= render template: 'layouts/application' %>